### ISSUE TITLE
reloadData() is not working

### ISSUE THREAD

**Issue by agshinrajabov** [JoniVR/VerticalCardSwiper#11]
`medias.observe(.value) { (snapshot) in
            guard let postsSnapshot = PostMedias(with: snapshot) else { return }
            self.medias = postsSnapshot.medias
            self.cardSwiper.reloadData()
        }`

my code is working but when I want to add Card Wiper using reload data, nothing is there.

**Comment by JoniVR** [comment]
hi @agshinrajabov 

I have just tested the `reloadData()` function inside the Example project and it seems to be working fine for me.

Things I tested: 
* Adding data and then reloading
* Removing data and then reloading
* Changing data and then reloading

As you seem to be working with Firebase, make sure you're actually receiving the data. 

You can test the `reloadData()` function yourself inside the Example if you feel like it.

The only thing `reloadData()` actually does internally is call `collectionView.reloadData()` so it should behave exactly the same way as a `UICollectionView` would.

If I have missed something, please let me know. 

Kind regards,
Joni

**edit:**
You might however want to try reloading on the main thread like this:
```swift
DispatchQueue.main.async {
    self.cardSwiper.reloadData()
}
```

Hope this helps.

**Comment by iAzaz96** [comment]
> hi @agshinrajabov
> 
> I have just tested the `reloadData()` function inside the Example project and it seems to be working fine for me.
> 
> Things I tested:
> 
> * Adding data and then reloading
> * Removing data and then reloading
> * Changing data and then reloading
> 
> As you seem to be working with Firebase, make sure you're actually receiving the data.
> 
> You can test the `reloadData()` function yourself inside the Example if you feel like it.
> 
> The only thing `reloadData()` actually does internally is call `collectionView.reloadData()` so it should behave exactly the same way as a `UICollectionView` would.
> 
> If I have missed something, please let me know.
> 
> Kind regards,
> Joni
> 
> **edit:**
> You might however want to try reloading on the main thread like this:
> 
> ```swift
> DispatchQueue.main.async {
>     self.cardSwiper.reloadData()
> }
> ```
> 
> Hope this helps.

the reload function is not working

**Comment by JoniVR** [comment]
Hi @iAzaz96 

Could you please share your code where you try to reload the data? 
It's working fine on the example and I really can't help you when you simply say "it's not working".
Make sure you reload it on the main thread, it should work exactly like a regular `UICollectionView`.

**Comment by iAzaz96** [comment]
self.getAllNames {

                self.activityIndicator.stopAnimating()

                print(self.AllahNames[0].Name)



                print(self.AllahNames.count)

                DispatchQueue.main.async {

                    self.cardSwiper.reloadData()

                }



            }
