### ISSUE TITLE
Programmatic Implementation

### ISSUE THREAD

**Issue by mavieth** [JoniVR/VerticalCardSwiper#15]
I have tried a few different methods, but do you have an entirely programmatic to load (and lazy load) and cardSwipe view controller?

Rather than 
```
@IBOutlet var cardSwiper: VerticalCardSwiper!
```

It would be something like 

```
var cardSwiper: VerticalCardSwiper = VerticalCardSwiper()
```

Thanks!

**Comment by JoniVR** [comment]
Hi @mavieth 

The [README.md](https://github.com/JoniVR/VerticalCardSwiper/blob/master/README.md) file doesn't use an IBOutlet, so I would recommend checking that out (especially the `Usage` section).
It should just work like that. The `VerticalCardSwiper` is a subclass of a `UIView` so you can treat it exactly like any other view when instantiating it. 
Let me know if you experience any further issues with this.

Kind regards,
Joni

**edit:**
Closing this for now, feel free to reopen.
