### ISSUE TITLE
Delegate issue?

### ISSUE THREAD

**Issue by richardpap** [JoniVR/VerticalCardSwiper#17]
Hey, 
After following the how to use section, I'm running into an error:
"Type 'XYViewController' does not conform to protocol 'VerticalCardSwiperDatasource'" and wants to add the "cardForItemAt" function, however, its implemented as it was described:

```
func cardForItemAt(verticalCardSwiperView: VerticalCardSwiperView, cardForItemAt index: Int) -> CardCell {
        let cardCell = verticalCardSwiperView.dequeueReusableCell(withReuseIdentifier: "ExampleCell", for: index) as! ExampleCardCel
        return cardCell
    }
```
This function has a warning btw: "Cast from 'UICollectionViewCell' to unrelated type 'ExampleCardCell' always fails"

The only difference in my code is that i dont use storyboard, so this is how the viewDidLoad looks like:

```
    override func viewDidLoad() {
        super.viewDidLoad()        
        cardSwiper = VerticalCardSwiper(frame: self.view.bounds)
        cardSwiper.datasource = self
        cardSwiper.register(ExampleCardCell.self, forCellWithReuseIdentifier: "ExampleCell")
    }
```

I'm experience this in xCode 10 and Swift 4.2

**Comment by JoniVR** [comment]
Hi @richardpap,

Quick question, what does your `ExampleCardCell` class look like? Does it inherit from `CardCell`?

If it doesn't, that should explain why you get the `Cast from 'UICollectionViewCell' to unrelated type 'ExampleCardCell' always fails"` message.

I just removed the .nib file and did the whole cell loading programmatically in the example and that seems to work for me so I think it should work. You could try comparing these projects and seeing where yours differs. 

You can find the modified (code-only cells) example version here:
[VerticalCardSwiper.zip](https://github.com/JoniVR/VerticalCardSwiper/files/2522278/VerticalCardSwiper.zip)

If you're still having issues after that, I'd be happy to help you out further, in that case, please let me know as many details as possible (for example what you're doing differently that could be causing this, error messages, warnings, ...)

Hope this helps.

Kinds regards,
Joni

**Comment by richardpap** [comment]
Thanks for the help!

I created a brand new project and implemented everything, however now i'm getting "Fatal error: Unexpectedly found nil while unwrapping an Optional value" error. The difference in my code is that i dont use storyboards at all. I've uploaded the project, you can check it
[cards.zip](https://github.com/JoniVR/VerticalCardSwiper/files/2522430/cards.zip)
:

**Comment by richardpap** [comment]
Hmm, i created a brand new project, implemented everything by your example and now it works. So something most be in my project causing this issue.

Thank you for the help!

Kind regards,
Richard

**Comment by JoniVR** [comment]
Any updates on this? Did you find the problem?

**Comment by richardpap** [comment]
Yep, I managed to fix it last night. I had a class called CardCell as well in my code, which caused the issue. Now everything works perfectly.

**Comment by JoniVR** [comment]
Alright, great to hear! 🎉
Closing this issue 🙂
