### ISSUE TITLE
Bug where sliding a card all the way to the side and releasing doesn't call "UIGestureRecognizerStateEnded".

### ISSUE THREAD

**Issue by JoniVR** [JoniVR/VerticalCardSwiper#2]
Sliding a card all the way to the side and releasing doesn't call "UIGestureRecognizerStateEnded". 

This causes the card to be stuck on the side. Reason for this bug is because the finger that is dragging the card is not in the card area anymore.

code inside
```
if let swipedCardIndex = collectionView.indexPathForItem(at: locationInCollectionView)
```
is not reached, which is why code inside .ended never gets executed.

**Comment by ranudhurandar** [comment]
Would it be possible for me to swipe to previous Viewcontroller while swiping the card  from left -> right. As I have three VC in sliding manner and the VerticalCardSwiper is implemented in the middle VC , after this implementation i am unable to swipe to previous VC. Help

**Comment by JoniVR** [comment]
I don't really understand what you're trying to say.. The VerticalCardSwiper is essentially a `UIView` with a `UICollectionView` inside it. 
So it behaves in the same way. All the other stuff depends on your implementation. 
I can't really help you with that.

**Comment by ranudhurandar** [comment]
Actually I have implemented this view in the middle view controller among
three...when I swipe to right side in middle View controller with
uigesturerecognizer , it didn't swipe to the first view controller like in
Pagination.

**Comment by JoniVR** [comment]
I'm assuming that the paged viewcontrollers are using a gesturerecognizer too? 
They're probably interfering with each other, you can see how `VerticalCardSwiper` handles this [here](https://github.com/JoniVR/VerticalCardSwiper/blob/f7f5ddf6156b7a2a0f627acbcf38908d6079bf26/Sources/VerticalCardSwiper.swift#L252). 

My guess is that you'll need to do the same thing with your code. Make sure you set `cardSwiper.isSideSwipingEnabled = false` (if you don't want card swiping, but I wouldn't enable it if you have sliding viewcontrollers already) and then implement the `shouldRecognizeSimultaneouslyWith` delegate method from `UIGestureRecognizerDelegate`. 

Again, I don't think this has anything to do with `VerticalCardSwiper`, it's just how `UIGestureRecognizer` works. 
See: https://stackoverflow.com/questions/41918256/handling-multiple-gesturerecognizers

**Comment by ranudhurandar** [comment]
Thank you so much..I appreciate your help.
