### ISSUE TITLE
Number of visible cards on the stack

### ISSUE THREAD

**Issue by Phuzer** [JoniVR/VerticalCardSwiper#24]
Is there anyway I can change the number of visible cards on the stack? The default is 2, the card that is showing and another one behind, and I need more than that. Help would be appreciated.

**Comment by JoniVR** [comment]
Hi @Phuzer 
Currently there isn't really a simple way to do it as far as I'm aware. 
I won't say it won't be supported in the future, but currently I want to prioritise other things like a stable release and insert/delete/move etc. 

Feel free to take a stab at it and create a PR, but I don't really have time to implement it right now. 
I'm sorry.

Best regards,
Joni

**Comment by Phuzer** [comment]
Ok, thanks for the response. I will try to implement it, do you have any quick suggestion how would you implement it or how it might work?

**Comment by JoniVR** [comment]
You'd probably have to dive into the code inside the `VerticalCardSwiperFlowLayout` and modify some of the math (probably in `updateCellAttributes`) there and add a variable that we can set so the user can pick whichever amount of visible cards he/she wants. 

It's probably also related to how the `UICollectionView` handles cell reuse so if you're unfamiliar with how that works, you might want to look at some of the Apple documentation on `UICollectionViewFlowLayout`, `UICollectionView`, ...

This is just my guess as I haven't really looked at this thoroughly. 
Again, I'm not saying that I won't consider implementing this in the future, but I'd currently rather focus on fixing as many bugs as possible and adding some more basic features for a stable release.

**Comment by JoniVR** [comment]
Closing for inactive, again, if anyone wants to take a stab at it, feel free to submit a PR or reopen in the future.
