### ISSUE TITLE
 I have problems adding the library to my podfile

### ISSUE THREAD

**Issue by STAMFORD313** [JoniVR/VerticalCardSwiper#25]
I have problems adding the library to my podfile

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Issue Description

![captura de pantalla 2018-11-18 a las 18 54 36](https://user-images.githubusercontent.com/45148076/48676186-698df200-eb63-11e8-8cd2-878104bc7001.png)

I enter pod 'VerticalCardSwiper', '0.1.0-beta6' in my podfile and it gives me an error [!] Unable to find a specification for `VerticalCardSwiper (= 0.1.0-beta6)`

### Environment

- **iOS Version**: [12.1]
- **Device(s)**: [mac mini]
- **Xcode Version**: [10.1]

**Comment by darnfish** [comment]
Can you try run `pod repo update` in the project directory?

**Comment by STAMFORD313** [comment]
I do not understand

**Comment by darnfish** [comment]
On the window in the left of your screenshot, type `pod repo update`, press enter, and then try `pod install` again.

**Comment by STAMFORD313** [comment]
ok

**Comment by STAMFORD313** [comment]
thank you very much is ready, it was missing that, again thank you very much

**Comment by darnfish** [comment]
No problem!
