### ISSUE TITLE
How to automatically scroll the third card when entering the page?

### ISSUE THREAD

**Issue by Jinxiansen** [JoniVR/VerticalCardSwiper#30]
Hello!
I want to scroll to the specified item, but I read https://github.com/JoniVR/VerticalCardSwiper/issues/23 this answer and found that there is no `cardSwiper.scrollToCard` method... 🤔
![3](https://user-images.githubusercontent.com/16829428/50556980-4c7c3f80-0d1b-11e9-82d2-0ce2c9a4b403.png)

> English is not my native language; please excuse typing errors.

**Comment by JoniVR** [comment]
Hi @Jinxiansen 

Yes, this function is not yet released, there is a bug that needs to be fixed before I can release it. 
If you want to experiment with it or try it out, you should you use the [development branch](https://github.com/JoniVR/VerticalCardSwiper/tree/development). 

You can also just use the development branch in your CocoaPods podfile like this:
```rb
pod 'VerticalCardSwiper', :git => 'https://github.com/JoniVR/VerticalCardSwiper.git', :branch => 'development'
```
There is currently still a problem with this function so I don't really recommend using it, although there are some workarounds described in the other issue.

If you have further questions about this, please post them in #23, I'll close this issue as it's essentially a duplicate. 

Hope this helps.

Happy holidays,
Joni

**Comment by Jinxiansen** [comment]
alright, thank you very much!
Looking forward to your release version.
