### ISSUE TITLE
CardSwiper.reloadData () does not work

### ISSUE THREAD

**Issue by STAMFORD313** [JoniVR/VerticalCardSwiper#31]
CardSwiper.reloadData() does not work

### New problem checklist

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub problems](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Description of the problem

CardSwiper.reloadData() does not work
Attempt to download data from the database and load before the card number function and do not reload after displaying the number of letters,
Please help !!
Thank you

### Ambient

- **Version for iOS**: 10.13.6
- **Device(s)**: Mac Mini
- **Xcode Version**: Version 10.1

**Comment by JoniVR** [comment]
Hi @STAMFORD313 	

It's pretty hard to help you without seeing your code, so it would be better to add the code that is causing the issue in here.

If you haven't done so already, make sure you call the function on a background thread. UIKit isn't thread safe. Like this:
```swift
DispatchQueue.main.async {
    cardSwiper.reloadData()
}
```

<hr>

But this is probably something with your own code and not an issue with the Library as this function does nothing more than call the underlying `reloadData()` function of the `UICollectionView`.

This is what it does under the hood: 
```swift
public func reloadData(){
   verticalCardSwiperView.reloadData()
}
``` 

So I think you're better off [searching for your problem on stackoverflow](https://www.google.com/search?q=site:stackoverflow.com%20collectionview%20reloaddata%20not%20working&cad=h).

Hope this helps.

Best regards
Joni

**edit:** closing for now as not enough detail is provided and I don't feel like it's a bug with the library, feel free to reopen if you feel like it's still a problem with the library itself.
