### ISSUE TITLE
Disable scrolling

### ISSUE THREAD

**Issue by andynadheer** [JoniVR/VerticalCardSwiper#33]
Is there a way to disable scrolling to the next card? For instance if tapped the first card, then you are allowed to scroll to next card. After you have scrolled to the second card, you have to tap that card to be able to scroll to third card, etc.

**Comment by JoniVR** [comment]
So you only want to allow user scrolling by tapping a card if I understand correctly?

**Comment by JoniVR** [comment]
If that is the case, you can do it like this:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
	cardSwiper.verticalCardSwiperView.isScrollEnabled = false
}

// implement VerticalCardSwiperDelegate to use this function
func didTapCard(verticalCardSwiperView: VerticalCardSwiperView, index: Int) {
    cardSwiper.scrollToCard(at: index + 1, animated: true)
}
```

**Comment by andynadheer** [comment]
Yes thank you! 👍
