### ISSUE TITLE
Allow user to set custom amount of visible cells in background

### ISSUE THREAD

**Issue by mohit196** [JoniVR/VerticalCardSwiper#40]
I want to display 3 cells at a single point of time.

### New Issue Checklist

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Issue Description

Right now I can display one cell at the background and I want to display 2 or 3 cells.

**Comment by JoniVR** [comment]
It's something that might be a nice addition to be able to allow the user to set how many cells should be visible.

I currently have some other stuff that I want to prioritize over this, but anyone is welcome to make a Pull Request to implement it :)
