### ISSUE TITLE
CardCell animation glitch when changing alpha

### ISSUE THREAD

**Issue by hemo87** [JoniVR/VerticalCardSwiper#43]
I'm trying to animate the cardCell with a basic flip animation, with alpha change to show/hide the other view. This works perfectly with UICollectionView.

https://github.com/hemo87/ExampleAnimation

![IMG_0989](https://user-images.githubusercontent.com/9624935/55746470-a8004c80-5a31-11e9-8d7a-9a33be9816de.GIF)

But the same code with this library just won't work, it refuses to do the alpha animation, as shown here.

https://github.com/hemo87/ExampleWithVeticalCardSwiper

![IMG_0990](https://user-images.githubusercontent.com/9624935/55746481-afbff100-5a31-11e9-94c6-25c71f65a3ea.GIF)

Im assuming this is a bug as I'd expect it to still behave like UICollectionView?

**Comment by JoniVR** [comment]
Hi @hemo87 

It should work as it is in fact a `UICollectionView` underneath it. 
Could always be some conflicting things of course.

I tried the example project in your Github link but the project looks empty to me, am I missing something? An example project would be ideal to help you out.

Kind regards,
Joni

**Comment by hemo87** [comment]
Thanks for the reply @JoniVR  not sure why they’re empty. I’ll re push them today

**Comment by hemo87** [comment]
I’ve quickly re pushed it. Should be working now.

**Comment by JoniVR** [comment]
Found the issue, will be pushing a bug fix soon and a release later :)

**Comment by JoniVR** [comment]
Just letting you know that version 1.0.0 has been released which fixes this issue 😉
