### ISSUE TITLE
Can I off the animation when the previous card goes behind?

### ISSUE THREAD

**Issue by jinios** [JoniVR/VerticalCardSwiper#44]
### New Issue Checklist

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Issue Description
Can I off the animation when the previous card goes behind?

I tried to find an option so that I can on/off the scale&fade animation when the cards goes behind but I couldn't.
So I triedn to comment out the codes regards animation and changing scale in the file `CardCell.swift`, but it seems disable animation is not working. 
I commented out the logic in the function named `resetToCenterPosition()`, and `animateCard(angle:, horizontalTranslation:)`

Please point out if anything wrong, or anything that I missed. 

### Environment

- **iOS Version**: [12.1.4]
- **Device(s)**: [iPhoneX]
- **Xcode Version**: [10.2.1]

**Comment by JoniVR** [comment]
Do you mean this?
 ![example](https://user-images.githubusercontent.com/7591717/56917160-0e214200-6abb-11e9-9155-75df39783347.png)

**Comment by JoniVR** [comment]
If that is what you mean, try:
```swift
/// The transform animation that is shown on the top card when scrolling through the cards. Default is 0.05.
cardSwiper.firstItemTransform = 0.00
```

As described in [the properties section of the readme](https://github.com/JoniVR/VerticalCardSwiper#properties).

Best regards,
Joni

**Comment by jinios** [comment]
Thanks a lot, I read it but I couldn't notice that was an enable/disable property for the previous card fading animation. I appreciate you develop this library and also your quick feedback.  
I will close this issue :)

Regards,
Mijin
