### ISSUE TITLE
Method func didSwipeCardAway not called

### ISSUE THREAD

**Issue by GianDiapason** [JoniVR/VerticalCardSwiper#49]
### New Issue Checklist

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Bug Description
In spite cardSwiper.delegate is set to self correctly, the method willSwipeCardAway and didSwipeCardAway are not called while didEndScroll and didScroll are called. 
Is there a dependency on some properties at a base of this behaviour? Any idea?

### Environment

- **iOS Version**: [IOS 12.3.1]
- **Device(s)**: [Iphone XS]
- **Xcode Version**: [10.2.1]

**Comment by JoniVR** [comment]
Hi @GianDiapason!

I'm not seeing an issue with these functions in the example app. 
Did you try testing it in the example?

Are you inheriting from `CardCell` for your cards? Is the delegate hooked up before you're trying to swipe away? 
There are lots of factors that can cause this, but I don't think it's a project specific issue but rather a bug in your code somewhere. Try going over the example app and find the difference with your implementation if you can't find it. I'm willing to help you search for it but it's pretty hard to help without having a look at your code.

If you think it's a project specific issue please provide me with a test project I can use to verify the issue.

**Comment by GianDiapason** [comment]
Hi JoniVR,
I found the problem and solve it. It was due to an active map (can be zoomed and scrooled) contained in the card. 
Sorry for the inconvenience
