### ISSUE TITLE
Universal app - iPad display cell size

### ISSUE THREAD

**Issue by alessign** [JoniVR/VerticalCardSwiper#5]
Hi Joni,

I came across little problem, not a bug. I want to make my app universal using your repo and everything works just fine, except I am not sure if I like the large cells on iPad display. It's too chunky for my app and what it offers. I tried to make the cell smaller just for the iPad in `layoutSubviews()` method in the UICollectionViewCell class:

```
if Device.isIpad() == true{
            let screenSize: CGRect = UIScreen.main.bounds
            self.frame = CGRect(x: (screenSize.width / 2) - 185, y: 0, width: 370, height: 700)
        }

 ```

As you can see, I want to keep the cell size on the iPad similar to what's on the iPhone, just slightly larger. It resizes to what I am intending to do, but only the first cell. The rest of the cells are back to the original specs - almost full screen. Where do I need to make the necessary changes  in the code, so all the cells will be affected please?

Thank you for your time and advice

A.

**Comment by JoniVR** [comment]
Hi @alessign,

I'm currently working on making this framework developer friendly and easy to use to allow these kinds of things (see development branch) and I haven't tested it to work on iPad, that's planned for the future.

However, if you need a solution to do this now, I'd suggest changing some things in the `sizeForItem` function of the `UICollectionViewDelegateFlowLayout` extension inside `HomeVC`.

```swift

extension HomeVC: UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        let cellWidth = collectionView.frame.size.width - (sideInset * 2)
        let cellHeight = collectionView.frame.size.height - flowLayout.minimumLineSpacing - visibleNextCardHeight - topInset
        
        // set cellHeight in the custom flowlayout, we use this for paging calculations.
        flowLayout.cellHeight = cellHeight
        
        if swipeAbleArea == nil {
            // Calculate and set the swipeAbleArea. We use this to determine wheter the cell can be swiped to the sides or not.
            let swipeAbleAreaOriginY = collectionView.frame.origin.y + collectionView.contentInset.top
            swipeAbleArea = CGRect(x: 0, y: swipeAbleAreaOriginY, width: view.frame.width, height: cellHeight)
            centerX = swipeAbleArea.width/2
        }
        return CGSize(width: cellWidth, height: cellHeight)
    }
}

```

more specifically, you should change the size of the cells in these lines:
```swift
 let cellWidth = collectionView.frame.size.width - (sideInset * 2)
 let cellHeight = collectionView.frame.size.height - flowLayout.minimumLineSpacing - visibleNextCardHeight - topInset
```

So for example, if you only want the cells to take up half the width of the collectionview on iPad, you could do something like:

```swift
var cellWidth = nil

if Device.isIpad() {
    cellWidth = collectionView.frame.size.width/2 - (sideInset * 2)
} else {
    cellWidth = collectionView.frame.size.width - (sideInset * 2)
}
```
 Same goes for the height.
(also, you don't really need the `== true` part in your if statement, it's the same thing without it)

This should in theory solve your problem, but I haven't tested this, so let me know if it doesn't.

Best regards,
Joni

**Comment by alessign** [comment]
Splendid, that method worked! Thank you. And you're right, removing `== true` has the same result...cheers
