### ISSUE TITLE
Can i set transperent view above the right or left selection?

### ISSUE THREAD

**Issue by DhavalUmraliya** [JoniVR/VerticalCardSwiper#50]
I want to set the view on left or right swipe. in short  i need to differentiate like and dislike with Above view

**Comment by JoniVR** [comment]
Hi @DhavalUmraliya 	

If I understand your question correctly you should be able to do this using the `didDragCard` function from the `VerticalCardSwiperDelegate`. 

Then you can add your own subview on top of the card to show the like or dislike view how you want it. See the [VerticalCardSwiperDelegate documentation](https://github.com/JoniVR/VerticalCardSwiper#delegation).
