### ISSUE TITLE
How  to stop left and right swipe of the card? 

### ISSUE THREAD

**Issue by ranudhurandar** [JoniVR/VerticalCardSwiper#51]
### New Issue Checklist

- [ ] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

**Comment by JoniVR** [comment]
You can use `isSideSwipingEnabled` for that (property of `VerticalCardSwiper`. See the [documentation](https://github.com/JoniVR/VerticalCardSwiper#properties). 
![image](https://user-images.githubusercontent.com/7591717/60518591-1592e080-9ce2-11e9-8595-857cc262c7bc.png)

**Comment by ranudhurandar** [comment]
Thanks alot
