### ISSUE TITLE
[Question] How do I flip a CardCell?

### ISSUE THREAD

**Issue by nick70007** [JoniVR/VerticalCardSwiper#56]
### New Issue Checklist

- [ ] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [ ] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

**Comment by JoniVR** [comment]
Hi @nick70007 

I don't mean to be rude but I'm pretty sure you can find this answer on Google. This library is built with a `UICollectionView` and `CardCell` inherits from `UICollectionViewCell`.

Please use Google (or any other search engine) to find your answer as it's not library related and I'm not your personal programmer/research person. If you run into additional issues that are related to this library, feel free to reopen.

Kind regards,
Joni

**Comment by nick70007** [comment]
hello sir, but just want to ask is there any method in this library through which i can flip the card cell?

**Comment by nick70007** [comment]
ok related to this library, when i run the app the card is displayed but one after another, is there any settings in this library so that all the cards initially are behind each other

**Comment by nick70007** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-07-10 at 16 48 56](https://user-images.githubusercontent.com/52743988/60965121-a9902800-a332-11e9-838d-9fedb752f4f4.png)
its looking like this

**Comment by nick70007** [comment]
i want it to be one after another like in tinder

**Comment by JoniVR** [comment]
> Is there any method in this library through which i can flip the card cell?

You can use the `didTapCard` delegate method to detect a cell tap (as indicated in [the documentation](https://github.com/JoniVR/VerticalCardSwiper#delegation)) and then flip the card yourself, you can find on the internet on how to flip a `UICollectionViewCell`. 

> ok related to this library, when i run the app the card is displayed the documentations there any settings in this library so that all the cards initially are behind each other

> i want it to be one after another like in tinder

No this is not possible and is not what this library tries to do, use another library like [tispr-card-stack](https://github.com/tispr/tispr-card-stack) or [Kolada](https://github.com/Yalantis/Koloda).
