### ISSUE TITLE
CocoaPod Install Not Working

### ISSUE THREAD

**Issue by lurein** [JoniVR/VerticalCardSwiper#6]
Can no longer install with CocoaPods:
"Unable to find a specification for `VerticalCardSwiper"

**Comment by JoniVR** [comment]
Hi @lurein 

How did you try to install? Make sure you add the version behind it for now.
As we're still in beta, it's required to add the version behind the pod name. So it should be like this:
```ruby
pod 'VerticalCardSwiper', '0.1.0-beta1'
```

I'll be fixing this soon so you don't need the version behind it. 
I just tested this and it works on my end, but let me know if you're still having issues, then we'll figure it out. 

Best regards
Joni

**Comment by lurein** [comment]
Hi Joni, 

Yes I tried this as well and unfortunately it gave the same error.

Thanks, 
LP

**Comment by JoniVR** [comment]
Alright, I'll look into it and see if I can find anything, could you perhaps share your podfile (or parts of it) here if you don't mind?

**Comment by lurein** [comment]
platform :ios, '10.0'

target 'MyApp' do
use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Firestore'
    pod 'FirebaseUI'
    pod 'AlertOnboarding'
    pod 'LGButton'
    pod 'VerticalCardSwiper', '0.1.0-beta1'
end

**Comment by JoniVR** [comment]
Could you please try running:
```
pod repo update --verbose
``` 

if that doesn't help, try installing an earlier version to see if that works:
```
pod 'VerticalCardSwiper', '0.1.0-alpha2'
```

I'm not sure what's causing this at the moment as I made a test project and it seems to work on that version. Could it possibly be related to your Cocoapods version?

**Comment by JoniVR** [comment]
Hi @lurein 

Any updates on the issue? Otherwise I'll close it soon.

edit: closed, feel free to reopen.
