### ISSUE TITLE
Is it possible to count vertical swipe?

### ISSUE THREAD

**Issue by erdemgc** [JoniVR/VerticalCardSwiper#7]
Hello,

I need to know, I am at the end of the collection, is it possible somehow?

BR,

**Comment by JoniVR** [comment]
Hi @erdemgc 

This is currently not a built-in feature, but I'll look into adding it to the `VerticalCardSwiperDelegate` perhaps, as it might be useful.

For now, you could try doing something like this:

```swift
func cardForItemAt(verticalCardSwiperView: VerticalCardSwiperView, cardForItemAt index: Int) -> CardCell {
        
    if index + 1 == yourArray.count {
        // handle reaching the end?
    }

    let cardCell = verticalCardSwiperView.dequeueReusableCell(withReuseIdentifier: "ExampleCell", for: index) as! ExampleCardCell
                
    return cardCell
}
```

Keep in mind that I haven't tested if this works, so let me know if it doesn't.
Hope this helps.

Best regards
Joni

**Comment by erdemgc** [comment]
Instead I have added new methods to delegate ; didSwipeDown and didSwipeUp. It also works fine.

Thanks for the cooperation.

BR,

Erdem

**Comment by JoniVR** [comment]
Awesome, I'll try to add those soon, I'm closing this, feel free to reopen. 
Have a nice day.
