### ISSUE TITLE
Stop Left Swipe || Increase Card Size

### ISSUE THREAD

**Issue by veersr9** [JoniVR/VerticalCardSwiper#72]
How do I stop only left swipe. If I am doing this -> 

func willSwipeCardAway(card: CardCell, index: Int, swipeDirection: SwipeDirection) {
        
        switch swipeDirection{
        case SwipeDirection.Right:
            if index < arrayHome.count {
                arrayHome.remove(at: index)
            }
        default:
            print("do nothing because be we didn't drag left")
        }
    }

-> But this is freezing the screen . And How can I increase card size.

**Comment by JoniVR** [comment]
I don't think there's a way to block a swipe to either side as of yet. What exactly are you looking for? Should the card just animate back or not move in that direction at all? 

As for increasing the card size, you can use `sizeForItem` or change the `topInset` and `sideInset` properties.
