### ISSUE TITLE
How to preview card(cell) reload?[Question] 

### ISSUE THREAD

**Issue by milan-galitein** [JoniVR/VerticalCardSwiper#77]
### New Issue Checklist

- [ ] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [ ] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).
- [ ] I searched Google for a solution to my issue if applicable.

**Comment by JoniVR** [comment]
I'm not entirely sure what the question is.. Can you provide some more details? Use a video or screenshot if you're having trouble describing it 🙂.

**Comment by milan-galitein** [comment]
resolve my issue
