### ISSUE TITLE
[Bug] `isStackOnBottom` and `stackedCardsCount` not working on 2.3.0

### ISSUE THREAD

**Issue by IDontEatMeat** [JoniVR/VerticalCardSwiper#78]
Bottom stacking won't work anymore with 2.3.0. I had to downgrade after wasting 3 hours not knowing what is going on. If someone else encounters this issue it is because of the new version. stackedCardsCount and isStackOnBottom have no effect whatsoever.

**Comment by IDontEatMeat** [comment]
Bottom stacking won't work anymore with 2.3.0. I had to downgrade after wasting 3 hours not knowing what is going on. If someone else encounters this issue it is because of the new version. stackedCardsCount and isStackOnBottom have no effect whatsoever.

**Comment by JoniVR** [comment]
Hi, you are correct, I've discovered the issue was introduced in #76, will work on a fix.

**Comment by IDontEatMeat** [comment]
Thanks, great project btw 👍

**Comment by stfnhdr** [comment]
fixed issue in PR  #79

**Comment by IDontEatMeat** [comment]
awesome thanks

**Comment by JoniVR** [comment]
This is now fixed in the new release, thanks @stfnhdr for opening a PR and @IDontEatMeat for reporting!
