### ISSUE TITLE
MJRefresh failed to refresh.

### ISSUE THREAD

**Issue by o1xhack** [JoniVR/VerticalCardSwiper#87]
### New Issue Checklist

- [ x] I updated VerticalCardSwiper to the latest version.
- [x ] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x ] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [ x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Bug Description
Describe the bug in detail.

### To Reproduce
Add Normal MJRefresh to cardSwiper.verticalCardSwiperView.
add endRefreshed to the data-loading func.
keeping refreshing but not going to the end it. or cannot add it

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Xcode Version**: [INSERT XCODE VERSION HERE]

**Comment by JoniVR** [comment]
This doesn't seem to have much to do with the codebase.. if you can provide a demo project that shows the issue is with VerticalCardSwiper, let me know and I'll reopen the issue.
