### ISSUE TITLE
Ability to add cards at runtime

### ISSUE THREAD

**Issue by erdemgc** [JoniVR/VerticalCardSwiper#9]
Hello,

There is a tiny bug that prevents users to add item at a runtime.

In order to fix this, I have changed 

this;
```swift
public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        
    return self.numberOfCards
}
```
to this:
```swift
public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        
     return datasource?.numberOfCards(verticalCardSwiperView: verticalCardSwiperView) ?? 0
}
```
BR,

Erdem

**Comment by JoniVR** [comment]
Hi, 

Thanks for reporting!

 I've had issues with this function before so I'll look into fixing this in the near future.

All the best,
Joni

**Comment by mightymango** [comment]
I've been able to get this working by adding the following to the VC:

```
    @IBAction func addCard(_ sender: Any) {
        
        cardSwiper.verticalCardSwiperView?.performBatchUpdates({
            cardSwiper.datasource = nil
            let indexPath = IndexPath(row: self.cardsDemoData.count, section: 0)
            
            cardsDemoData.append(Card(text: "This is a new card!"))
            cardSwiper.verticalCardSwiperView?.insertItems(at: [indexPath])
            
            cardSwiper.datasource = self
            
        }, completion: nil)
        
    }
```

By setting the datasource to nil while inserting the item and then setting it back correctly it seems to work around this issue.

**Comment by JoniVR** [comment]
Thanks for posting your solution, I have this almost completely implemented in a git stash somewhere but I was still finishing up some minor stuff and fixing some other things before releasing that, just for future reference that this should be supported pretty soon.

**Comment by darnfish** [comment]
I just tested this and it works really well!

**Comment by JoniVR** [comment]
@williamsthing Yeah, I'm not sure when I'll merge this to master, I actually wanted to test a bit more in-depth and possibly even add some extra UITests for it with a settings UI in the example, but I'm not sure yet, could also add those in a later version.

**Comment by JoniVR** [comment]
This will be released with the next beta version, I'll probably add some extra UITests and Unit tests and then fix the animation glitch at the end of the stack, when those things are fixed, I'm probably going to release the first non-beta version (0.1.0).
